AllCops:
  Exclude:
    - 'app/controllers/graphql_controller.rb'
    - 'test/**/*'
    - 'node_modules/**/*'
    - 'bin/*'
    - 'vendor/**/*'
  NewCops: enable
Style/Documentation:
  Enabled: false
Style/SingleArgumentDig:
  Enabled: false
Metrics/LineLength:
  Max: 100
require:
  - rubocop-rails
  - rubocop-rspec