development:
  adapter: postgresql
  database: repo_search_api_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: repo_search_api_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: repo_search_api_production
  pool: 5
  timeout: 5000